"""Initial tables

Revision ID: 589999c98b38
Revises: 
Create Date: 2026-04-17 15:57:04.035504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '589999c98b38'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    autoincrement=True)
    op.alter_column('users', 'login',
                    existing_type=mysql.TEXT(),
                    type_=sa.String(length=200),
                    nullable=False)
    op.alter_column('users', 'registration_date',
                    existing_type=mysql.TEXT(),
                    type_=sa.Date(),
                    nullable=False)
    # op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_unique_constraint(None, 'users', ['login'])
    op.alter_column('credits', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('credits', 'user_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('credits', 'issuance_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('credits', 'return_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('credits', 'body',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)
    op.alter_column('credits', 'percent',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               nullable=False)
    # op.create_index(op.f('ix_credits_id'), 'credits', ['id'], unique=False)
    op.create_foreign_key(None, 'credits', 'users', ['user_id'], ['id'])
    op.alter_column('dictionary', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('dictionary', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=10),
               nullable=False)
    op.alter_column('payments', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('payments', 'sum',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Numeric(precision=15, scale=2),
               nullable=False)
    op.alter_column('payments', 'payment_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('payments', 'credit_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'type_id',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Integer(),
               nullable=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_foreign_key(None, 'payments', 'credits', ['credit_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'dictionary', ['type_id'], ['id'])
    op.alter_column('plans', 'period',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('plans', 'sum',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Numeric(precision=15, scale=2),
               nullable=False)
    op.alter_column('plans', 'category_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.create_foreign_key(None, 'plans', 'dictionary', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'registration_date',
               existing_type=sa.Date(),
               type_=mysql.TEXT(),
               nullable=True)
    op.alter_column('users', 'login',
               existing_type=sa.String(length=200),
               type_=mysql.TEXT(),
               nullable=True)
    op.alter_column('users', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'plans', type_='foreignkey')
    op.alter_column('plans', 'category_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=True)
    op.alter_column('plans', 'sum',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=mysql.DOUBLE(asdecimal=True),
               nullable=True)
    op.alter_column('plans', 'period',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.alter_column('payments', 'type_id',
               existing_type=sa.Integer(),
               type_=mysql.DOUBLE(asdecimal=True),
               nullable=True)
    op.alter_column('payments', 'credit_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('payments', 'payment_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('payments', 'sum',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=mysql.DOUBLE(asdecimal=True),
               nullable=True)
    op.alter_column('payments', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('dictionary', 'name',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('dictionary', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'credits', type_='foreignkey')
    op.drop_index(op.f('ix_credits_id'), table_name='credits')
    op.alter_column('credits', 'percent',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               nullable=True)
    op.alter_column('credits', 'body',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DOUBLE(asdecimal=True),
               nullable=True)
    op.alter_column('credits', 'return_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('credits', 'issuance_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('credits', 'user_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=True)
    op.alter_column('credits', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
